spring.application.name=Journal App

#mongodb connection
spring.data.mongodb.uri=mongodb+srv://cyron:g5ek2necYfFeZ9p3@cluster0.jod7m.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017

spring.data.mongodb.database=journalDB
spring.data.mongodb.auto-index-creation=true

#spring.security.user.name=cyron
#spring.security.user.password=cyron


#mongodb+srv://cyron:<db_password>@cluster0.jod7m.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0