spring.application.name=Journal App

#mongodb connection
spring.data.mongodb.uri=mongodb+srv://cyro:r2CmjVDoqonuQi4I@cluster0.jod7m.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

spring.data.mongodb.database=journalDB
spring.data.mongodb.auto-index-creation=true

#if auth if needed then
#spring.data.mongodb.username=username
#spring.data.mongodb.password=userpass

#r2CmjVDoqonuQi4I